# Database
spring.datasource.url=jdbc:postgresql://postgres-service:5432/medisync
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Redis Caching
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# Feign Clients
notification-service.url=${NOTIFICATION_SERVICE_URL}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
