server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 1. Reporting Service
            - id: reporting-route
              uri: http://localhost:8082
              order: 1
              predicates:
                - Path=/api/reports/**

            # 2. Notification Service
            - id: notification-route
              uri: http://localhost:8081
              order: 2
              predicates:
                - Path=/api/notifications/**

            # 3. Core Service (The Catch-all)
            - id: core-route
              uri: http://localhost:8080
              order: 10
              predicates:
                - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: "*"